---
format: 
  html:
    embed-resources: true
execute:
  echo: true
code-fold: true
title: Lab 5: Insurance Costs
author: James Compagno
jupyter: python3
---

In [180]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [181]:
lr = LinearRegression()


ames = pd.read_csv("AmesHousing.csv")
X = ames[["Gr Liv Area", "TotRms AbvGrd"]]
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train_s = (X_train - X_train.mean())/X_train.std()

lr_fitted = lr.fit(X_train_s, y_train)
lr_fitted.coef_

array([ 72829.84009875, -19320.19793351])

In [182]:
ames.head()

Order        PID  MS SubClass  ... Sale Type  Sale Condition  SalePrice
0      1  526301100           20  ...       WD           Normal     215000
1      2  526350040           20  ...       WD           Normal     105000
2      3  526351010           20  ...       WD           Normal     172000
3      4  526353030           20  ...       WD           Normal     244000
4      5  527105010           60  ...       WD           Normal     189900

[5 rows x 82 columns]

In [183]:
new_house = pd.DataFrame(data = {"Gr Liv Area": [889], "TotRms AbvGrd": [6]})
new_house

Gr Liv Area  TotRms AbvGrd
0          889              6

In [184]:
new_house_s = (new_house - new_house.mean())/new_house.std()
new_house_s

Gr Liv Area  TotRms AbvGrd
0          NaN            NaN

In [185]:
X_test_s = (X_test - X_train.mean())/X_train.std()
y_preds = lr_fitted.predict(X_test_s)

r2_score(y_test, y_preds)

0.5136474646729811

In [186]:
new_house_s = (new_house - X_train.mean())/X_train.std()
lr_fitted.predict(new_house_s)

array([98361.41516052])

In [187]:
lr_pipeline = Pipeline(
  [("standardize", StandardScaler()),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('standardize', StandardScaler()),
                ('linear_regression', LinearRegression())])

In [188]:
lr_pipeline_fitted = lr_pipeline.fit(X_train, y_train)

y_preds = lr_pipeline_fitted.predict(X_test)
r2_score(y_test, y_preds)

0.5136474646729811

In [189]:
lr_pipeline_fitted.predict(new_house)

array([98361.41516052])

In [190]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
)

lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('dummify',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Bldg Type']),
                                                 ('standardize',
                                                  StandardScaler(),
                                                  ['Gr Liv Area',
                                                   'TotRms AbvGrd'])])),
                ('linear_regression', LinearRegression())])

In [191]:
X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_fitted = lr_pipeline.fit(X_train, y_train)

In [192]:
ct_fitted = ct.fit(X_train)

ct.transform(X_train)

array([[ 1.        ,  0.        ,  0.        , ...,  0.        , -0.03593684,
        -0.28287775],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.06165322,
        -0.28287775],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  1.42000579,
         0.98804745],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,  0.42893615,
         1.62351006],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  1.7780569 ,
         0.98804745],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.12825234,
         0.35258485]], shape=(2197, 7))

In [193]:
ct.transform(X_test)

array([[ 1.        ,  0.        ,  0.        , ...,  0.        , -0.08539141,
         0.35258485],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.69796902,
         0.35258485],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.94326371,
         0.35258485],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.0062641 ,
         0.35258485],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.16451873,
         0.35258485],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -1.0823956 ,
        -1.55380296]], shape=(733, 7))

In [194]:
lr_pipeline_fitted.named_steps['linear_regression'].coef_

array([ 72813.26337381, -19315.80048314])

In [195]:
type(y_preds)

numpy.ndarray

In [196]:
lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
).set_output(transform="pandas")


ct.fit_transform(X_train)

dummify__Bldg Type_1Fam  ...  standardize__TotRms AbvGrd
361                       1.0  ...                   -0.282878
822                       1.0  ...                   -0.282878
1614                      1.0  ...                    0.988047
258                       1.0  ...                    0.352585
2202                      1.0  ...                    0.352585
...                       ...  ...                         ...
1990                      1.0  ...                    1.623510
1744                      1.0  ...                   -0.282878
1515                      0.0  ...                    1.623510
1769                      1.0  ...                    0.988047
927                       1.0  ...                    0.352585

[2197 rows x 7 columns]

In [197]:
ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_inter.fit_transform(X_train)

interaction__1  ...  interaction__Gr Liv Area TotRms AbvGrd
361              1.0  ...                                  8886.0
822              1.0  ...                                  8808.0
1614             1.0  ...                                 17736.0
258              1.0  ...                                 11774.0
2202             1.0  ...                                 10052.0
...              ...  ...                                     ...
1990             1.0  ...                                 14778.0
1744             1.0  ...                                  7596.0
1515             1.0  ...                                 15444.0
1769             1.0  ...                                 19184.0
927              1.0  ...                                 10948.0

[2197 rows x 4 columns]

In [198]:
ct_dummies = ColumnTransformer(
  [("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"])],
  remainder = "passthrough"
).set_output(transform = "pandas")

ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["remainder__TotRms AbvGrd", "dummify__Bldg Type_1Fam"]),
  ],
  remainder = "drop"
).set_output(transform = "pandas")

X_train_dummified = ct_dummies.fit_transform(X_train)
X_train_dummified

dummify__Bldg Type_1Fam  ...  remainder__Sale Condition
361                       1.0  ...                     Normal
822                       1.0  ...                     Normal
1614                      1.0  ...                     Normal
258                       1.0  ...                     Normal
2202                      1.0  ...                     Normal
...                       ...  ...                        ...
1990                      1.0  ...                    Abnorml
1744                      1.0  ...                    Partial
1515                      0.0  ...                     Normal
1769                      1.0  ...                     Normal
927                       1.0  ...                     Normal

[2197 rows x 85 columns]

In [199]:
ct_inter.fit_transform(X_train_dummified)

interaction__1  ...  interaction__remainder__TotRms AbvGrd dummify__Bldg Type_1Fam
361              1.0  ...                                                6.0            
822              1.0  ...                                                6.0            
1614             1.0  ...                                                8.0            
258              1.0  ...                                                7.0            
2202             1.0  ...                                                7.0            
...              ...  ...                                                ...            
1990             1.0  ...                                                9.0            
1744             1.0  ...                                                6.0            
1515             1.0  ...                                                0.0            
1769             1.0  ...                                                8.0            
927              1.0  ...                                                7.0            

[2197 rows x 4 columns]

Make Your own Size and Number of Rooms

In [200]:
model_library = {}
records = []

In [201]:
ct_1 = ColumnTransformer(
  [
    ("select", "passthrough", ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop")

In [202]:
lr_pipeline = Pipeline(
  [("select", ct_1),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('select',
                 ColumnTransformer(transformers=[('select', 'passthrough',
                                                  ['Gr Liv Area',
                                                   'TotRms AbvGrd'])])),
                ('linear_regression', LinearRegression())])

In [203]:
X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_fitted = lr_pipeline.fit(X_train, y_train)
model_library["LivArea_Rooms"] = lr_fitted 

In [204]:
y_test_pred = model_library["LivArea_Rooms"].predict(X_test)
mse = mean_squared_error(y_test, y_test_pred) 
records.append({
    "Model": "LivArea_Rooms", "Split": "Test",
    "RMSE": np.sqrt(mse), "MSE": mse, "R2": r2_score(y_test, y_test_pred)  
})

In [205]:
cumulative_models = (pd.DataFrame(records))
cumulative_models

Model Split          RMSE           MSE        R2
0  LivArea_Rooms  Test  55373.843704  3.066263e+09  0.524547

# Using size, number of rooms, and building type.

In [206]:
preprocess = ColumnTransformer(
    [
        ("dummify", OneHotEncoder(sparse_output=False), ["Bldg Type"]),
        ("num", "passthrough", ["Gr Liv Area", "TotRms AbvGrd"]),
    ],
    remainder="drop",
    verbose_feature_names_out=False,
).set_output(transform="pandas")

lr_pipeline = Pipeline([
    ("preprocess", preprocess),
    ("linear_regression", LinearRegression())
])

lr_fitted = lr_pipeline.fit(X_train, y_train)
model_library["LivArea_Rooms_BlgdType"] = lr_fitted 

In [208]:
y_test_pred = model_library["LivArea_Rooms_BlgdType"].predict(X_test)
mse = mean_squared_error(y_test, y_test_pred) 
records.append({
    "Model": "LivArea_Rooms_BlgdType", "Split": "Test",
    "RMSE": np.sqrt(mse), "MSE": mse, "R2": r2_score(y_test, y_test_pred)  
})

In [209]:
cumulative_models = (pd.DataFrame(records))
cumulative_models

Model Split          RMSE           MSE        R2
0           LivArea_Rooms  Test  55373.843704  3.066263e+09  0.524547
1  LivArea_Rooms_BlgdType  Test  53380.249826  2.849451e+09  0.558166

# Using size and building type, and their interaction.

In [ ]:
preprocess = ColumnTransformer(
    [
        ("dummify", OneHotEncoder(sparse_output=False), ["Bldg Type"]),
        ("num", "passthrough", ["Gr Liv Area", "TotRms AbvGrd"]),
    ],
    remainder="drop",
    verbose_feature_names_out=False,
).set_output(transform="pandas")

interaction 

In [ ]:
lr_pipeline = Pipeline([
    ("preprocess", preprocess),
    ("linear_regression", LinearRegression())
])

In [ ]:
lr_fitted = lr_pipeline.fit(X_train, y_train)
model_library["LivArea_Rooms_BlgdType"] = lr_fitted 

In [ ]:
y_test_pred = model_library["LivArea_Rooms_BlgdType"].predict(X_test)
mse = mean_squared_error(y_test, y_test_pred) 
records.append({
    "Model": "LivArea_Rooms_BlgdType", "Split": "Test",
    "RMSE": np.sqrt(mse), "MSE": mse, "R2": r2_score(y_test, y_test_pred)  
})

cumulative_models = (pd.DataFrame(records))
cumulative_models

# MISSING WORK

Once again consider four modeling options for house price:

    -Using only the size and number of rooms.
    -Using size, number of rooms, and building type.
    -Using size and building type, and their interaction.
    -Using a 5-degree polynomial on size, a 5-degree polynomial on number of rooms, and also building type.
    
Use cross_val_score with the pipelines you made earlier to find the cross-validated root mean squared error for each model.

Which do you prefer? Does this agree with your conclusion from earlier?