In [58]:
import numpy as np
import pandas as pd

In [1]:
print(
  "99 Bottles of beer on the wall, 99 Bottles of beer. Take one down, pass it around, 98 Bottles of beer on the wall. 98 Bottles of beer on the wall, 98 Bottles of beer. Take one down, pass it around, 97 Bottles of beer on the wall." #... etc etc etc
)

99 Bottles of beer on the wall, 99 Bottles of beer. Take one down, pass it around, 98 Bottles of beer on the wall. 98 Bottles of beer on the wall, 98 Bottles of beer. Take one down, pass it around, 97 Bottles of beer on the wall.


In [3]:
for i in range(100,3,-1):
  print(str(i) + " bottles of beer on the wall")
  print(str(i) + " bottles of beer")
  print(" take one down, pass it around,")
  print(str(i-1) + " bottles of beer on the wall")

100 bottles of beer on the wall
100 bottles of beer
 take one down, pass it around,
99 bottles of beer on the wall
99 bottles of beer on the wall
99 bottles of beer
 take one down, pass it around,
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
 take one down, pass it around,
97 bottles of beer on the wall
97 bottles of beer on the wall
97 bottles of beer
 take one down, pass it around,
96 bottles of beer on the wall
96 bottles of beer on the wall
96 bottles of beer
 take one down, pass it around,
95 bottles of beer on the wall
95 bottles of beer on the wall
95 bottles of beer
 take one down, pass it around,
94 bottles of beer on the wall
94 bottles of beer on the wall
94 bottles of beer
 take one down, pass it around,
93 bottles of beer on the wall
93 bottles of beer on the wall
93 bottles of beer
 take one down, pass it around,
92 bottles of beer on the wall
92 bottles of beer on the wall
92 bottles of beer
 take one down, pass it around,
91 bottles o

In [5]:
def sing_verse(i):
  
    """
    Rescales a numeric vector to have a max of 1 and min of 0
    
    Parameter
    ---------
    verse : num
        A number from 1 to 100 representing the number of beer on the wall.

    Returns
    -------
    array 
        A song containing the values.
    """

    print(str(i) + " bottles of beer on the wall")
    print(str(i) + " bottles of beer")
    print(" take one down, pass it around,")
    print(str(i-1) + " bottles of beer on the wall")
  
    return sing_verse

In [6]:
sing_verse(13)

13 bottles of beer on the wall
13 bottles of beer
 take one down, pass it around,
12 bottles of beer on the wall


<function __main__.sing_verse(i)>

In [15]:
#hers

i = 100

def sing_verse2(i):
  song = str(i) + " bottles of beer on the wall \n" + str(i) + " bottles of beer \n" + " take one down, pass it around, \n" + str(i-1) + " bottles of beer on the wall \n"
  
  return song

In [17]:
song = ""

for i in range(100,97,-1):
  song = song + sing_verse2(i)
  
print(song)

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 



In [41]:
song = []

for i in range(100,97,-1):
  new_verse = sing_verse2(i)
  song.append(new_verse)
  
print(song)

['100 bottles of beer on the wall \n100 bottles of beer \n take one down, pass it around, \n99 bottles of beer on the wall \n', '99 bottles of beer on the wall \n99 bottles of beer \n take one down, pass it around, \n98 bottles of beer on the wall \n', '98 bottles of beer on the wall \n98 bottles of beer \n take one down, pass it around, \n97 bottles of beer on the wall \n']


In [20]:
song

['100 bottles of beer on the wall \n100 bottles of beer \n take one down, pass it around, \n99 bottles of beer on the wall \n',
 '99 bottles of beer on the wall \n99 bottles of beer \n take one down, pass it around, \n98 bottles of beer on the wall \n',
 '98 bottles of beer on the wall \n98 bottles of beer \n take one down, pass it around, \n97 bottles of beer on the wall \n']

7.2.1 Vectorized functions

In [22]:
a_num = 5
a_vec = [1,3,5,7]

np.sqrt(a_num)
np.sqrt(a_vec)


array([1.        , 1.73205081, 2.23606798, 2.64575131])

In [23]:
result = []
for i in a_vec:
  result = result + [np.sqrt(i)]
  
result

[np.float64(1.0),
 np.float64(1.7320508075688772),
 np.float64(2.23606797749979),
 np.float64(2.6457513110645907)]

In [29]:
a_vec = np.array([-2, 1, -3, -9, 7])

for val in a_vec:
  if val > 0:
    val = np.sqrt(val)
  print(val)

-2
1.0
-3
-9
2.6457513110645907


In [25]:
is_pos = a_vec > 0

a_vec[is_pos] = np.sqrt(a_vec[is_pos])

a_vec

array([-2,  1, -3, -9,  2])

In [30]:
a_vec = np.array([-2, 1, -3, -9, 7])

In [39]:
def sqrt_pos_unvec(val):
    if val > 0:
        val = np.sqrt(val)
    return val

In [36]:
def sqrt_pos_vec(vec_array):
    is_pos = a_vec > 0
    a_vec[is_pos] = np.sqrt(a_vec[is_pos])

    return is_pos

In [37]:
sqrt_pos_vec(100)

array([False,  True, False, False,  True])

In [44]:
song = map(sing_verse2, range(100, 97, -1))
song = list(song)
print("".join(song))

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 



In [49]:
nums = range(100, 97, -1)
drinks = ["beer", "milk", "lemonade"]
song = map(sing_verse_3, nums, drinks)
print("".join(list(song)))

100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of milk on the wall 
99 bottles of milk
 take one down, pass it around, 
98 bottles of milk on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 



In [48]:
def sing_verse_3(num, drink):
  song = str(num) + " bottles of " + drink + " on the wall \n"
  song = song + str(num) + " bottles of " + drink + "\n" 
  song = song + " take one down, pass it around, \n"
  song = song + str(num-1) + " bottles of " + drink + " on the wall \n"
  
  return song

In [65]:
def sing_verse_4(num, containers, drink):
  song = str(num) + " " + containers + " of " + drink + " on the wall \n"
  song = song + str(num) + " " + containers + " of " + drink + "\n" 
  song = song + " take one down, pass it around, \n"
  song = song + str(num-1) + " " + containers + " of "+ drink + " on the wall \n"
  
  return song

In [66]:
nums = range(100, 97, -1)
containers = ["bottles", "cartons", "glasses"]
drinks = ["beer", "milk", "lemonade"]
song = map(sing_verse_4, nums, containers, drinks)
print("".join(list(song)))

100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 cartons of milk on the wall 
99 cartons of milk
 take one down, pass it around, 
98 cartons of milk on the wall 
98 glasses of lemonade on the wall 
98 glasses of lemonade
 take one down, pass it around, 
97 glasses of lemonade on the wall 



Lambda here

Iterating on datasets

In [70]:
dat = pd.DataFrame({"x": [99, 50, 2], "y": [1, 2, 3]})

dat.apply(np.sqrt)

x         y
0  9.949874  1.000000
1  7.071068  1.414214
2  1.414214  1.732051

In [71]:
dat.apply(np.sum, axis=1)

0    100
1     52
2      5
dtype: int64

In [72]:
dat = pd.DataFrame({"num": [99, 50, 2], "drink": ["beer", "soda", "Capri Sun"], "container": ["bottles", "cans", "pouches"]})

dat

num      drink container
0   99       beer   bottles
1   50       soda      cans
2    2  Capri Sun   pouches

In [77]:
dat.apply(lambda x: sing_verse_4(x['num'], x['drink'], x['container']), axis=1)

0    99 beer of bottles on the wall \n99 beer of bo...
1    50 soda of cans on the wall \n50 soda of cans\...
2    2 Capri Sun of pouches on the wall \n2 Capri S...
dtype: object